// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StaplesProject2MVC.Models;

#nullable disable

namespace StaplesProject2MVC.Migrations
{
    [DbContext(typeof(PokemonDBContext))]
    [Migration("20241021023627_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StaplesProject2MVC.Models.Pokemon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Attack")
                        .HasColumnType("int");

                    b.Property<int?>("Defense")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Hp")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SpAttack")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("SpDefense")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Speed")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Pokemons");

                    b.HasData(
                        new
                        {
                            Id = 815,
                            Attack = 116,
                            Defense = 75,
                            Hp = 80,
                            Name = "Cinderace",
                            SpAttack = 65,
                            SpDefense = 75,
                            Speed = 119
                        },
                        new
                        {
                            Id = 812,
                            Attack = 125,
                            Defense = 90,
                            Hp = 100,
                            Name = "Rillaboom",
                            SpAttack = 60,
                            SpDefense = 70,
                            Speed = 85
                        },
                        new
                        {
                            Id = 818,
                            Attack = 85,
                            Defense = 65,
                            Hp = 70,
                            Name = "Inteleon",
                            SpAttack = 125,
                            SpDefense = 65,
                            Speed = 120
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
